version: '3.8'

services:
  redis:
    container_name: 'funnelbase_redis'
    image: redis:7.2.5-alpine3.20
    restart: always
    #    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
#    volumes:
#      - ./redis.conf:/usr/local/etc/redis/redis.conf