// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: api/funnelbase.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMethod int32

const (
	RequestMethod_GET  RequestMethod = 0
	RequestMethod_POST RequestMethod = 1
)

// Enum value maps for RequestMethod.
var (
	RequestMethod_name = map[int32]string{
		0: "GET",
		1: "POST",
	}
	RequestMethod_value = map[string]int32{
		"GET":  0,
		"POST": 1,
	}
)

func (x RequestMethod) Enum() *RequestMethod {
	p := new(RequestMethod)
	*p = x
	return p
}

func (x RequestMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_api_funnelbase_proto_enumTypes[0].Descriptor()
}

func (RequestMethod) Type() protoreflect.EnumType {
	return &file_api_funnelbase_proto_enumTypes[0]
}

func (x RequestMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestMethod.Descriptor instead.
func (RequestMethod) EnumDescriptor() ([]byte, []int) {
	return file_api_funnelbase_proto_rawDescGZIP(), []int{0}
}

type RequestPriority int32

const (
	RequestPriority_LOW    RequestPriority = 0
	RequestPriority_MEDIUM RequestPriority = 1
	RequestPriority_HIGH   RequestPriority = 2
)

// Enum value maps for RequestPriority.
var (
	RequestPriority_name = map[int32]string{
		0: "LOW",
		1: "MEDIUM",
		2: "HIGH",
	}
	RequestPriority_value = map[string]int32{
		"LOW":    0,
		"MEDIUM": 1,
		"HIGH":   2,
	}
)

func (x RequestPriority) Enum() *RequestPriority {
	p := new(RequestPriority)
	*p = x
	return p
}

func (x RequestPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_api_funnelbase_proto_enumTypes[1].Descriptor()
}

func (RequestPriority) Type() protoreflect.EnumType {
	return &file_api_funnelbase_proto_enumTypes[1]
}

func (x RequestPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestPriority.Descriptor instead.
func (RequestPriority) EnumDescriptor() ([]byte, []int) {
	return file_api_funnelbase_proto_rawDescGZIP(), []int{1}
}

type Headers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Headers) Reset() {
	*x = Headers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_funnelbase_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Headers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Headers) ProtoMessage() {}

func (x *Headers) ProtoReflect() protoreflect.Message {
	mi := &file_api_funnelbase_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Headers.ProtoReflect.Descriptor instead.
func (*Headers) Descriptor() ([]byte, []int) {
	return file_api_funnelbase_proto_rawDescGZIP(), []int{0}
}

func (x *Headers) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Headers) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url           string          `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        RequestMethod   `protobuf:"varint,2,opt,name=method,proto3,enum=requester.RequestMethod" json:"method,omitempty"`
	Body          string          `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Authorization string          `protobuf:"bytes,4,opt,name=authorization,proto3" json:"authorization,omitempty"`
	Headers       []*Headers      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	Priority      RequestPriority `protobuf:"varint,6,opt,name=priority,proto3,enum=requester.RequestPriority" json:"priority,omitempty"`
	// time in milliseconds for the response to exist in cache assuming its successful
	// if no cacheLifespan is provided, it will not access any existing cache however it will update any existing cache
	CacheLifespan int32 `protobuf:"varint,7,opt,name=cacheLifespan,proto3" json:"cacheLifespan,omitempty"`
	// url for the single version of a batch request
	// ex. if the url of the request was https://api.spotify.com/v1/albums?ids=a,b,c (this fetches multiple albums),
	// the batchItemUrl should be the url that only fetches 1 album, ex. 'https://api.spotify.com/v1/albums/{batchItemId}'
	BatchItemUrl string `protobuf:"bytes,8,opt,name=batchItemUrl,proto3" json:"batchItemUrl,omitempty"`
	// following the Spotify albums API spec, the batchArrayId identifies where the array starts in the JSON response from spotify
	// ex. response
	// {
	//    "albums": [
	//      ...
	//    ]
	// }
	//
	// for the above example, the batchArrayId would be 'albums'
	BatchArrayId string `protobuf:"bytes,9,opt,name=batchArrayId,proto3" json:"batchArrayId,omitempty"`
	// following the Spotify albums API spec, the batchItemId identifies which field inside the objects inside the batchArrayId is the id
	// ex. response
	// {
	//    "albums": [
	//      {
	//        "album_type": "album",
	//        "id": "abc"
	//      },
	//      ...
	//    ]
	// }
	//
	// for the above example, the batchItemId would be 'id'
	BatchItemId string `protobuf:"bytes,10,opt,name=batchItemId,proto3" json:"batchItemId,omitempty"`
	// URL param inside the batch request URL that identifies the list of items
	// for the Spotify album API, the batch request url is https://api.spotify.com/v1/albums?ids=a,b,c
	// for the above example, the batchParamId would be 'ids'
	BatchParamId string `protobuf:"bytes,11,opt,name=batchParamId,proto3" json:"batchParamId,omitempty"`
	// name of the interface which the request should be added to
	Interface string `protobuf:"bytes,12,opt,name=interface,proto3" json:"interface,omitempty"`
	// name of the rate limit the request should be added to
	RateLimit string `protobuf:"bytes,13,opt,name=rateLimit,proto3" json:"rateLimit,omitempty"`
	// number of tries if the request fails
	Retries int32 `protobuf:"varint,14,opt,name=retries,proto3" json:"retries,omitempty"`
	// name of the client sending the request
	Client string `protobuf:"bytes,15,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_funnelbase_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_funnelbase_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_funnelbase_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetMethod() RequestMethod {
	if x != nil {
		return x.Method
	}
	return RequestMethod_GET
}

func (x *Request) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Request) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *Request) GetHeaders() []*Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetPriority() RequestPriority {
	if x != nil {
		return x.Priority
	}
	return RequestPriority_LOW
}

func (x *Request) GetCacheLifespan() int32 {
	if x != nil {
		return x.CacheLifespan
	}
	return 0
}

func (x *Request) GetBatchItemUrl() string {
	if x != nil {
		return x.BatchItemUrl
	}
	return ""
}

func (x *Request) GetBatchArrayId() string {
	if x != nil {
		return x.BatchArrayId
	}
	return ""
}

func (x *Request) GetBatchItemId() string {
	if x != nil {
		return x.BatchItemId
	}
	return ""
}

func (x *Request) GetBatchParamId() string {
	if x != nil {
		return x.BatchParamId
	}
	return ""
}

func (x *Request) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Request) GetRateLimit() string {
	if x != nil {
		return x.RateLimit
	}
	return ""
}

func (x *Request) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *Request) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32      `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	CacheHit   bool       `protobuf:"varint,2,opt,name=cacheHit,proto3" json:"cacheHit,omitempty"`
	Body       string     `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Headers    []*Headers `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_funnelbase_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_funnelbase_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_funnelbase_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *Response) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Response) GetHeaders() []*Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

type RateLimit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the interface
	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// name of the rate limit
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// status code from the api to tell the client to backoff as its hitting rate limits
	BackoffStatusCode int32 `protobuf:"varint,3,opt,name=backoffStatusCode,proto3" json:"backoffStatusCode,omitempty"` // 429
	// the header received from the api telling the client how long to wait before sending more requests
	RetryAfterHeader string `protobuf:"bytes,4,opt,name=retryAfterHeader,proto3" json:"retryAfterHeader,omitempty"` // Retry-After
	// time in milliseconds that the rate limit is based on
	Period int64 `protobuf:"varint,5,opt,name=period,proto3" json:"period,omitempty"`
	// number of requests per limit that will be allowed through
	Limit int32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *RateLimit) Reset() {
	*x = RateLimit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_funnelbase_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimit) ProtoMessage() {}

func (x *RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_api_funnelbase_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimit.ProtoReflect.Descriptor instead.
func (*RateLimit) Descriptor() ([]byte, []int) {
	return file_api_funnelbase_proto_rawDescGZIP(), []int{3}
}

func (x *RateLimit) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *RateLimit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RateLimit) GetBackoffStatusCode() int32 {
	if x != nil {
		return x.BackoffStatusCode
	}
	return 0
}

func (x *RateLimit) GetRetryAfterHeader() string {
	if x != nil {
		return x.RetryAfterHeader
	}
	return ""
}

func (x *RateLimit) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *RateLimit) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Interface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Interface) Reset() {
	*x = Interface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_funnelbase_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_api_funnelbase_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_api_funnelbase_proto_rawDescGZIP(), []int{4}
}

func (x *Interface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InterfaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *InterfaceResponse) Reset() {
	*x = InterfaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_funnelbase_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceResponse) ProtoMessage() {}

func (x *InterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_funnelbase_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceResponse.ProtoReflect.Descriptor instead.
func (*InterfaceResponse) Descriptor() ([]byte, []int) {
	return file_api_funnelbase_proto_rawDescGZIP(), []int{5}
}

func (x *InterfaceResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type RateLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *RateLimitResponse) Reset() {
	*x = RateLimitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_funnelbase_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitResponse) ProtoMessage() {}

func (x *RateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_funnelbase_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitResponse.ProtoReflect.Descriptor instead.
func (*RateLimitResponse) Descriptor() ([]byte, []int) {
	return file_api_funnelbase_proto_rawDescGZIP(), []int{6}
}

func (x *RateLimitResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_api_funnelbase_proto protoreflect.FileDescriptor

var file_api_funnelbase_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x22, 0x31, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x8f, 0x04, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x30, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c,
	0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x36, 0x0a, 0x08,
	0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a,
	0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f,
	0x72, 0x69, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x4c, 0x69, 0x66,
	0x65, 0x73, 0x70, 0x61, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x72, 0x6c, 0x12, 0x22,
	0x0a, 0x0c, 0x62, 0x61, 0x74, 0x63, 0x68, 0x41, 0x72, 0x72, 0x61, 0x79, 0x49, 0x64, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x61, 0x74, 0x63, 0x68, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x61, 0x74, 0x63, 0x68, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x61, 0x74, 0x63,
	0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x63, 0x68, 0x65, 0x48, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x61, 0x63, 0x68, 0x65, 0x48, 0x69, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x2c, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x22, 0xc5, 0x01, 0x0a, 0x09, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x2c, 0x0a, 0x11, 0x62, 0x61, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x62, 0x61,
	0x63, 0x6b, 0x6f, 0x66, 0x66, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x2a, 0x0a, 0x10, 0x72, 0x65, 0x74, 0x72, 0x79, 0x41, 0x66, 0x74, 0x65, 0x72, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65, 0x74, 0x72, 0x79,
	0x41, 0x66, 0x74, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x1f, 0x0a, 0x09, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x11, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2f, 0x0a, 0x11, 0x52,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x22, 0x0a, 0x0d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x07, 0x0a,
	0x03, 0x47, 0x45, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x01,
	0x2a, 0x30, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x49, 0x47, 0x48,
	0x10, 0x02, 0x32, 0xd3, 0x01, 0x0a, 0x0a, 0x46, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x62, 0x61, 0x73,
	0x65, 0x12, 0x39, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0c,
	0x41, 0x64, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x14, 0x2e, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x1a, 0x1c, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x44, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x14, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x7a, 0x65, 0x70, 0x68,
	0x6f, 0x73, 0x2f, 0x66, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_funnelbase_proto_rawDescOnce sync.Once
	file_api_funnelbase_proto_rawDescData = file_api_funnelbase_proto_rawDesc
)

func file_api_funnelbase_proto_rawDescGZIP() []byte {
	file_api_funnelbase_proto_rawDescOnce.Do(func() {
		file_api_funnelbase_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_funnelbase_proto_rawDescData)
	})
	return file_api_funnelbase_proto_rawDescData
}

var file_api_funnelbase_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_funnelbase_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_funnelbase_proto_goTypes = []any{
	(RequestMethod)(0),        // 0: requester.RequestMethod
	(RequestPriority)(0),      // 1: requester.RequestPriority
	(*Headers)(nil),           // 2: requester.Headers
	(*Request)(nil),           // 3: requester.Request
	(*Response)(nil),          // 4: requester.Response
	(*RateLimit)(nil),         // 5: requester.RateLimit
	(*Interface)(nil),         // 6: requester.Interface
	(*InterfaceResponse)(nil), // 7: requester.InterfaceResponse
	(*RateLimitResponse)(nil), // 8: requester.RateLimitResponse
}
var file_api_funnelbase_proto_depIdxs = []int32{
	0, // 0: requester.Request.method:type_name -> requester.RequestMethod
	2, // 1: requester.Request.headers:type_name -> requester.Headers
	1, // 2: requester.Request.priority:type_name -> requester.RequestPriority
	2, // 3: requester.Response.headers:type_name -> requester.Headers
	3, // 4: requester.Funnelbase.QueueRequest:input_type -> requester.Request
	6, // 5: requester.Funnelbase.AddInterface:input_type -> requester.Interface
	5, // 6: requester.Funnelbase.AddRateLimit:input_type -> requester.RateLimit
	4, // 7: requester.Funnelbase.QueueRequest:output_type -> requester.Response
	7, // 8: requester.Funnelbase.AddInterface:output_type -> requester.InterfaceResponse
	8, // 9: requester.Funnelbase.AddRateLimit:output_type -> requester.RateLimitResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_funnelbase_proto_init() }
func file_api_funnelbase_proto_init() {
	if File_api_funnelbase_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_funnelbase_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Headers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_funnelbase_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_funnelbase_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_funnelbase_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RateLimit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_funnelbase_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Interface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_funnelbase_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*InterfaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_funnelbase_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RateLimitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_funnelbase_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_funnelbase_proto_goTypes,
		DependencyIndexes: file_api_funnelbase_proto_depIdxs,
		EnumInfos:         file_api_funnelbase_proto_enumTypes,
		MessageInfos:      file_api_funnelbase_proto_msgTypes,
	}.Build()
	File_api_funnelbase_proto = out.File
	file_api_funnelbase_proto_rawDesc = nil
	file_api_funnelbase_proto_goTypes = nil
	file_api_funnelbase_proto_depIdxs = nil
}
